/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp dbusinterface.xml -i dbusinterface.h -a DBusInterfaceAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "DBusInterfaceAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class LoaderAdaptor
 */

LoaderAdaptor::LoaderAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

LoaderAdaptor::~LoaderAdaptor()
{
    // destructor
}

EDII::IPCQtDBus::ABIVersion LoaderAdaptor::abiVersion()
{
    // handle method call edii.loader.abiVersion
    EDII::IPCQtDBus::ABIVersion abiVersion;
    QMetaObject::invokeMethod(parent(), "abiVersion", Q_RETURN_ARG(EDII::IPCQtDBus::ABIVersion, abiVersion));
    return abiVersion;
}

EDII::IPCQtDBus::DataPack LoaderAdaptor::loadData(const QString &formatTag, int loadOption)
{
    // handle method call edii.loader.loadData
    EDII::IPCQtDBus::DataPack pack;
    QMetaObject::invokeMethod(parent(), "loadData", Q_RETURN_ARG(EDII::IPCQtDBus::DataPack, pack), Q_ARG(QString, formatTag), Q_ARG(int, loadOption));
    return pack;
}

EDII::IPCQtDBus::DataPack LoaderAdaptor::loadDataFile(const QString &formatTag, const QString &filePath, int loadOption)
{
    // handle method call edii.loader.loadDataFile
    EDII::IPCQtDBus::DataPack pack;
    QMetaObject::invokeMethod(parent(), "loadDataFile", Q_RETURN_ARG(EDII::IPCQtDBus::DataPack, pack), Q_ARG(QString, formatTag), Q_ARG(QString, filePath), Q_ARG(int, loadOption));
    return pack;
}

EDII::IPCQtDBus::DataPack LoaderAdaptor::loadDataHint(const QString &formatTag, const QString &hint, int loadOption)
{
    // handle method call edii.loader.loadDataHint
    EDII::IPCQtDBus::DataPack pack;
    QMetaObject::invokeMethod(parent(), "loadDataHint", Q_RETURN_ARG(EDII::IPCQtDBus::DataPack, pack), Q_ARG(QString, formatTag), Q_ARG(QString, hint), Q_ARG(int, loadOption));
    return pack;
}

EDII::IPCQtDBus::SupportedFileFormatVec LoaderAdaptor::supportedFileFormats()
{
    // handle method call edii.loader.supportedFileFormats
    EDII::IPCQtDBus::SupportedFileFormatVec supportedFileFormats;
    QMetaObject::invokeMethod(parent(), "supportedFileFormats", Q_RETURN_ARG(EDII::IPCQtDBus::SupportedFileFormatVec, supportedFileFormats));
    return supportedFileFormats;
}

