/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp dbusinterface.xml -i dbusinterface.h -p DBusInterfaceInterface
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DBUSINTERFACEINTERFACE_H
#define DBUSINTERFACEINTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "dbusinterface.h"

/*
 * Proxy class for interface edii.loader
 */
class EdiiLoaderInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "edii.loader"; }

public:
    EdiiLoaderInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~EdiiLoaderInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<EDII::IPCQtDBus::ABIVersion> abiVersion()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("abiVersion"), argumentList);
    }

    inline QDBusPendingReply<EDII::IPCQtDBus::DataPack> loadData(const QString &formatTag, int loadOption)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(formatTag) << QVariant::fromValue(loadOption);
        return asyncCallWithArgumentList(QStringLiteral("loadData"), argumentList);
    }

    inline QDBusPendingReply<EDII::IPCQtDBus::DataPack> loadDataFile(const QString &formatTag, const QString &filePath, int loadOption)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(formatTag) << QVariant::fromValue(filePath) << QVariant::fromValue(loadOption);
        return asyncCallWithArgumentList(QStringLiteral("loadDataFile"), argumentList);
    }

    inline QDBusPendingReply<EDII::IPCQtDBus::DataPack> loadDataHint(const QString &formatTag, const QString &hint, int loadOption)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(formatTag) << QVariant::fromValue(hint) << QVariant::fromValue(loadOption);
        return asyncCallWithArgumentList(QStringLiteral("loadDataHint"), argumentList);
    }

    inline QDBusPendingReply<EDII::IPCQtDBus::SupportedFileFormatVec> supportedFileFormats()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("supportedFileFormats"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace edii {
  typedef ::EdiiLoaderInterface loader;
}
#endif
