/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp dbusinterface.xml -i dbusinterface.h -a DBusInterfaceAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUSINTERFACEADAPTOR_H
#define DBUSINTERFACEADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "dbusinterface.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface edii.loader
 */
class LoaderAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "edii.loader")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"edii.loader\">\n"
"    <method name=\"loadData\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"formatTag\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"loadOption\"/>\n"
"      <arg direction=\"out\" type=\"(bsa(sssssssa(dd)))\" name=\"pack\"/>\n"
"      <annotation value=\"EDII::IPCQtDBus::DataPack\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"loadDataHint\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"formatTag\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"hint\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"loadOption\"/>\n"
"      <arg direction=\"out\" type=\"(bsa(sssssssa(dd)))\" name=\"pack\"/>\n"
"      <annotation value=\"EDII::IPCQtDBus::DataPack\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"loadDataFile\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"formatTag\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"filePath\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"loadOption\"/>\n"
"      <arg direction=\"out\" type=\"(bsa(sssssssa(dd)))\" name=\"pack\"/>\n"
"      <annotation value=\"EDII::IPCQtDBus::DataPack\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"supportedFileFormats\">\n"
"      <arg direction=\"out\" type=\"a(sssa(s))\" name=\"supportedFileFormats\"/>\n"
"      <annotation value=\"EDII::IPCQtDBus::SupportedFileFormatVec\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"abiVersion\">\n"
"      <arg direction=\"out\" type=\"(ii)\" name=\"abiVersion\"/>\n"
"      <annotation value=\"EDII::IPCQtDBus::ABIVersion\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    LoaderAdaptor(QObject *parent);
    virtual ~LoaderAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    EDII::IPCQtDBus::ABIVersion abiVersion();
    EDII::IPCQtDBus::DataPack loadData(const QString &formatTag, int loadOption);
    EDII::IPCQtDBus::DataPack loadDataFile(const QString &formatTag, const QString &filePath, int loadOption);
    EDII::IPCQtDBus::DataPack loadDataHint(const QString &formatTag, const QString &hint, int loadOption);
    EDII::IPCQtDBus::SupportedFileFormatVec supportedFileFormats();
Q_SIGNALS: // SIGNALS
};

#endif
